version: '3.8'

networks:
  wdio:
    name: wdio

services:

  selenoid:
    image: aerokube/selenoid:1.10.1
    # image: selenoid:latest
    container_name: selenoid
    volumes:
      - "./selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-container-network", "wdio",
    ]
    ports:
      - "4444"
    networks:
      - wdio

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.3
    command: ["--selenoid-uri", "http://selenoid:4444"]
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    networks:
      - wdio
